# Generated by Django 4.2 on 2023-05-12 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField()),
                ('metadata', models.TextField()),
                ('timestamp', models.CharField(max_length=13)),
                ('client_agent', models.TextField()),
                ('client_ip', models.TextField()),
            ],
        ),
    ]
