# Generated by Django 4.2 on 2023-05-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExplainPythonCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error', models.IntegerField()),
                ('msg', models.CharField(max_length=255)),
                ('data', models.CharField(max_length=255)),
            ],
        ),
    ]
